@baseUrl = http://pmangeot-server.eddi.cloud/api-docs/
@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}


# @name login
POST {{baseUrl}}/login
content-type: application/json

{
    "email": "Romeo.Renard89@yahoo.fr",
    "password": "secret"
}

###

# @name register
POST {{baseUrl}}/signin
content-type: application/json
Authorization: Bearer

{
  "name": "G",
  "firstname": "S",
  "email": "Eddie33@gmail.com",
  "pseudo": "Ata5",
  "password": "secret",
  "description": "Vieux loup de mer",
  "availability": true,
  "tags": [ 1, 2 ]
}

###

# @name getUsers
GET {{baseUrl}}/api/users
content-type: application/json
Authorization: Bearer 

###

# @name getOneUser
GET {{baseUrl}}/api/users/80
content-type: application/json
Authorization: Bearer 

###

# @name editUser
PUT {{baseUrl}}/api/users/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoiRmVsaXg4N0B5YWhvby5mciIsImlkIjoxfSwiaWF0IjoxNjg3ODQ5MjA1LCJleHAiOjE2ODc5MDMyMDV9.ybE2tVLGf6NCpOw7XwxpCucvnkJL_KRBO6Q0C5kEMxM

{
  "name": "E",
  "firstname": "Haddock",
  "email": "Charline.Prevost@gmail.com",
  "pseudo": "Bloup",
  "password": "",
  "description": "Vieille louve de mer",
  "availability": false,
  "tags": [
    1,
    3,
    4
  ]
}

###

# @name deleteUser
DELETE {{baseUrl}}/api/users/1
content-type: application/json
Authorization: Bearer 

###

# @name getProjects
GET {{baseUrl}}/api/projects
content-type: application/json
Authorization: Bearer 

###

# @name getOneProject
GET {{baseUrl}}/api/projects/1
content-type: application/json
Authorization: Bearer 

###

# @name createProject
POST {{baseUrl}}/api/projects
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoiUm9tZW8uUmVuYXJkODlAeWFob28uZnIiLCJpZCI6OTB9LCJpYXQiOjE2ODc4NTgwMDksImV4cCI6MTY4NzkxMjAwOX0.fUOGWL_U9tILciWjm3bJqEWawlSAuaYsomXLqW3wYV8

{
  "title": "Bloup",
  "availability": true,
  "description": "Lore mipsumb labla",
  "user_id": 90,
  "tags": [
    2,
    3,
    4
  ]
}

###

# @name editProject
PUT {{baseUrl}}/api/projects/5
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoiUm9tZW8uUmVuYXJkODlAeWFob28uZnIiLCJpZCI6OTB9LCJpYXQiOjE2ODc4NTgwMDksImV4cCI6MTY4NzkxMjAwOX0.fUOGWL_U9tILciWjm3bJqEWawlSAuaYsomXLqW3wYV8

{
  "title": "Bisc",
  "availability": true,
  "description": "Loreum blabla",
  "user_id": 2,
  "tags": [
    3,
    6,
    4
  ]
}

###

# @name deleteProject
DELETE {{baseUrl}}/api/projects/1
content-type: application/json
Authorization: Bearer 

###

# @name applyToProject
POST {{baseUrl}}/api/projects/1/user/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoicGFub0ByYW1peC5nYSIsImlkIjozfSwiaWF0IjoxNjg3NDI4NDYzLCJleHAiOjE2ODc0ODI0NjN9.rZSsmaEGXHmI1z8gcqxoZrSLDGykM_cKgYxUK89nNT8

###

# @name addUserToProject
PUT {{baseUrl}}/api/projects/1/user/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoiY2FwdGFpbkBnbWFpbC5jb20iLCJpZCI6Mn0sImlhdCI6MTY4NzQyODEzMiwiZXhwIjoxNjg3NDgyMTMyfQ._XQgPEyfHOAOzBY-uXzYz_gSazIDA1jjbXrcYRL-mCc

###

# @name removeUserToProject
DELETE {{baseUrl}}/api/projects/1/user/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoiY2FwdGFpbkBnbWFpbC5jb20iLCJpZCI6Mn0sImlhdCI6MTY4NzQyODEzMiwiZXhwIjoxNjg3NDgyMTMyfQ._XQgPEyfHOAOzBY-uXzYz_gSazIDA1jjbXrcYRL-mCc

###

POST {{baseUrl}}/refresh-token
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "refreshToken": "{{refreshToken}}"
}
